wetty:
  image: nathanleclaire/wetty
  ports: 
    - "3000:3000"
  environment:
    VIRTUAL_PORT: 3000
    VIRTUAL_HOST: thephedds.com

nginx:
  image: jwilder/nginx-proxy
  volumes: 
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports: 
    - "80:80"
